import { Groq } from "groq-sdk";
import * as fs from "fs";
import * as path from "path";
import { glob } from "glob";

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

const DOCS_DIR = path.join(__dirname, "../docs");

async function generateDocumentation() {
  // 1. التأكد من وجود مجلد الـ docs
  if (!fs.existsSync(DOCS_DIR)) {
    fs.mkdirSync(DOCS_DIR);
  }

  const files = await glob("src/**/*.@(service|controller).ts");

  console.log(`🚀 Starting AI Documentation for ${files.length} files...`);

  for (const file of files) {
    const code = fs.readFileSync(file, "utf-8");
    const fileName = path.basename(file);
    
    console.log(`📝 Processing: ${fileName}`);

    try {
      const completion = await groq.chat.completions.create({
        messages: [
          {
            role: "system",
            content: `You are an expert Software Architect and Technical Writer. 
            Analyze the provided NestJS code and generate a high-quality GitHub Wiki page in Markdown.
            Include the following sections:
            1. **Overview**: Purpose of this file.
            2. **Architecture Role**: Is it a Controller (API Layer) or Service (Business Layer)?
            3. **Key Methods**: Explanation of each function, its parameters, and return types.
            4. **Dependencies**: What other services or modules does it inject?
            5. **Kafka/Events**: If there are any event emitters or listeners (Kafka), explain them clearly.
            Use professional, concise technical language.`
          },
          {
            role: "user",
            content: `File: ${fileName}\n\nCode Content:\n\`\`\`typescript\n${code}\n\`\`\``
          }
        ],
        model: "llama3-70b-8192",
        temperature: 0.2,
      });

      const markdownContent = completion.choices[0]?.message?.content;

      if (markdownContent) {
        const outputFileName = fileName.replace(".ts", ".md");
        const outputPath = path.join(DOCS_DIR, outputFileName);
        
        const finalContent = `> **Note**: This documentation is automatically generated by Argus AI Agent.\n\n${markdownContent}`;
        
        fs.writeFileSync(outputPath, finalContent);
        console.log(`✅ Generated: ${outputFileName}`);
      }
    } catch (error) {
      console.error(`❌ Error processing ${fileName}:`, error);
    }
  }

  console.log("\n✨ AI Documentation update complete!");
}

generateDocumentation();